### ISSUE TITLE
Can't save and test in Grafana

### ISSUE THREAD

**Issue by nikkadim** [mroject/freeswitch_exporter#15]
curl http://localhost:9282/metrics - works fine
but http://localhost:9282/metrics ias URL in Data Sources gives error:
` Error reading Prometheus: bad_response: readObjectStart: expect { or n, but found <, error found in #1 byte of ...|<html> <|..., bigger context ...|<html> <head><title>Node Exporter</title></head>|...
`

**Comment by mroject** [comment]
Prometheus is configured as follows:

```yaml
  - job_name: "freeswitch"
    static_configs:
      - targets: ["localhost:9282"]
```
